### ISSUE TITLE
Form to config extension saves nsec for autocomplete field after

### ISSUE THREAD

**Issue by antonioconselheiro** [neilck/aka-extension#5]
Form to config exntesion saves nsec for autocomplete field,
not sure if this is a bug, but I think this don't looks good.

*To reproduce*
 - include your nsec
 - save nsec
 - click to add new nsec
 - click in the nsec field
 - then old nsec is give as autocomplete:
![image](https://github.com/neilck/aka-extension/assets/91137293/5325782e-94e8-47d3-bf39-f295bd9c489a)

**Comment by neilck** [comment]
Change input to have autocomplete="off"

**Comment by neilck** [comment]
Updated with commit https://github.com/neilck/aka-extension/commit/bc8c17f36319f6a7c7115f0f2a461e9e787ea61a instead of merging pull request because JSX requires "autoComplete" instead of "autocomplete".
